/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'index', // Getting Started
    {
      type: 'category',
      label: 'APIs',
      items: [{type: 'autogenerated', dirName: 'api'}],
    },
    {
      type: 'category',
      label: 'Apps',
      items: [{type: 'autogenerated', dirName: 'apps'}],
    },
    {
      type: 'category',
      label: 'Storefront',
      items: [{type: 'autogenerated', dirName: 'storefront'}],
    },
    'webhooks', // Webhooks (single file)
    {
      type: 'category',
      label: 'Campaign Cart',
      items: [{type: 'autogenerated', dirName: 'campaign-cart'}],
    },
  ],
};

module.exports = sidebars;
