name: Build Search Index

on:
  push:
    branches:
      - main

jobs:
  algolia:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Get algolia as config
        id: algolia_config
        run: echo "::set-output name=config::$(cat algolia.json | jq -r tostring)"

      - name: Push indices to Algolia
        uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          CONFIG: ${{ steps.algolia_config.outputs.config }}

  index_apis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
        env:
            ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Update index
        working-directory: ./tools
        run: python update_api_docs.py
