name: Build Search Index

on:
  push:
    branches:
      - main

jobs:
  index:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Algolia index
        run: curl -f "https://developers.nextcommerce.com/api/algolia?token=${{ secrets.ALGOLIA_INDEX_SECRET }}"
